services:

  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      MYSQLHOST: db
      MYSQLDATABASE: vite_et_gourmand
      MYSQLUSER: root
      MYSQLPASSWORD: root
      MYSQLPORT: 3306

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vite_et_gourmand
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: