#!/bin/bash
set -e

mysql -uroot -p"$MYSQL_ROOT_PASSWORD" <<SQL
REVOKE ALL PRIVILEGES, GRANT OPTION
FROM '$MYSQL_USER'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE
ON \`$MYSQL_DATABASE\`.*
TO '$MYSQL_USER'@'%';
SQL